"""added should_not_post_to_discord

Revision ID: 1ad2a2386a5d
Revises: 188a6f34382b
Create Date: 2025-04-24 16:01:06.633778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad2a2386a5d'
down_revision: Union[str, None] = '188a6f34382b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_type', sa.Column('should_not_post_to_discord', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('publicity', sa.Column('should_not_post_to_discord', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicity', 'should_not_post_to_discord')
    op.drop_column('event_type', 'should_not_post_to_discord')
    # ### end Alembic commands ###
