"""Add discord_post_days_ahead to event

Revision ID: 1ade3392392a
Revises: 1ad2a2386a5d
Create Date: 2025-04-24 20:37:21.177281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ade3392392a'
down_revision: Union[str, None] = '1ad2a2386a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('discord_post_days_ahead', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'discord_post_days_ahead')
    # ### end Alembic commands ###
