name: Build and Publish Docker image

on:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/threadbound

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tags=${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}

